### ISSUE TITLE
MacOS Sierra

### ISSUE THREAD

**Issue by robbielove** [triplef/LastHistory#4]
Could you please push a version that works on Mac OS Sierra, I have upgraded and this application no longer works on the new OS.

**Comment by reven** [comment]
[MatthewCallis](https://github.com/MatthewCallis) has built a version that works on Sierra in his fork. Have a look at his repo: [MatthewCallis/LastHistory](https://github.com/MatthewCallis/LastHistory).

**Comment by robbielove** [comment]
Thank you.
